In [1]:
# Introduction to Pytorch


In [4]:
import torch
import numpy as np


In [5]:
a = np.ones(5)

In [6]:
a

array([1., 1., 1., 1., 1.])

In [7]:
b = torch.from_numpy(a)

In [8]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [9]:
x = torch.empty(5, 3)


In [10]:
x

tensor([[ 0.0000e+00,  1.0842e-19, -7.1973e-06],
        [-8.5920e+09,  1.1210e-44, -0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 1.4013e-45,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [11]:
x = torch.rand(5,3)

In [12]:
x

tensor([[0.5280, 0.3056, 0.2667],
        [0.5736, 0.1446, 0.6983],
        [0.5264, 0.2910, 0.5330],
        [0.0112, 0.3034, 0.6922],
        [0.3085, 0.3488, 0.2319]])

In [13]:
x = torch.zeros(5,3)

In [14]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])